variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonar

build:
  stage: build
  script:
    - ./gradlew assemble

test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestReport

sonarqube:
  stage: sonar
  script:
    - ./gradlew sonar "-Dsonar.host.url=http://localhost:9000" "-Dsonar.login=$SONAR_TOKEN"
  allow_failure: true



